// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhascoalottoDesafio.Infraestrutura.UnitOfWork;

namespace PhascoalottoDesafio.Infraestrutura.Migrations
{
    [DbContext(typeof(DbUnitOfWork))]
    [Migration("20201129164749_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("PhascoalottoDesafio.Dominio.Aggregates.ConfigurationAgg.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ComissionPercentage")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("InterestType")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaxInstallments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });
#pragma warning restore 612, 618
        }
    }
}
